package com.chapman.edu.commissions.api.rest.security;

import com.chapman.edu.commissions.model.UserRole;

import java.util.*;

/**
 * Authenticator implementation for JWT (JSON Web Token) Bearer tokens.
 *
 * This authenticator validates JWT tokens and extracts user information.
 * This is a simplified implementation for educational purposes.
 *
 * Design Pattern: Strategy Pattern
 * Concrete strategy for JWT authentication.
 *
 * Educational Note: This is a simplified JWT implementation.
 * Production systems should use libraries like:
 * - java-jwt (auth0)
 * - jjwt (io.jsonwebtoken)
 * - nimbus-jose-jwt
 *
 * These libraries provide:
 * - Proper signature verification
 * - Token expiration validation
 * - Claims extraction
 * - Key rotation support
 */
public class JwtAuthenticator implements Authenticator {

    private final String secretKey;
    private final Map<String, UserPrincipal> tokenCache; // Simplified token storage

    /**
     * Constructs a JWT authenticator.
     *
     * @param secretKey The secret key for JWT validation
     */
    public JwtAuthenticator(String secretKey) {
        this.secretKey = secretKey;
        this.tokenCache = new HashMap<>();
        initializeSampleTokens();
    }

    /**
     * Initializes sample tokens for demonstration purposes.
     * In production, tokens would be generated by a separate authentication service.
     */
    private void initializeSampleTokens() {
        // Sample token for sales rep
        tokenCache.put("sample-token-sales-rep",
            new UserPrincipal("USER-001", "john.doe", "john.doe@example.com",
                Set.of(UserRole.SALES_REP)));

        // Sample token for sales manager
        tokenCache.put("sample-token-manager",
            new UserPrincipal("USER-002", "jane.smith", "jane.smith@example.com",
                Set.of(UserRole.SALES_MANAGER)));

        // Sample token for admin
        tokenCache.put("sample-token-admin",
            new UserPrincipal("USER-003", "admin", "admin@example.com",
                Set.of(UserRole.SYSTEM_ADMIN, UserRole.FINANCE_ADMIN)));
    }

    @Override
    public Optional<UserPrincipal> authenticate(AuthenticationToken token) {
        if (!supports(token)) {
            return Optional.empty();
        }

        String jwt = token.getCredentials();
        if (jwt == null || jwt.isEmpty()) {
            return Optional.empty();
        }

        // Simplified JWT validation (educational purposes)
        // Production implementation would:
        // 1. Parse JWT structure (header.payload.signature)
        // 2. Verify signature using secret key
        // 3. Validate expiration time
        // 4. Validate issuer and audience
        // 5. Extract claims (user ID, roles, etc.)

        return validateAndExtractPrincipal(jwt);
    }

    @Override
    public String getSupportedScheme() {
        return "Bearer";
    }

    /**
     * Validates JWT and extracts user principal.
     *
     * Educational Implementation: Uses simple token lookup.
     *
     * Production Implementation would:
     * <pre>
     * try {
     *     DecodedJWT jwt = JWT.require(Algorithm.HMAC256(secretKey))
     *         .build()
     *         .verify(token);
     *
     *     String userId = jwt.getClaim("userId").asString();
     *     String username = jwt.getClaim("username").asString();
     *     List<String> roles = jwt.getClaim("roles").asList(String.class);
     *
     *     return Optional.of(new UserPrincipal(userId, username, email, roles));
     * } catch (JWTVerificationException e) {
     *     return Optional.empty();
     * }
     * </pre>
     *
     * @param jwt The JWT token string
     * @return Optional containing the principal, or empty if invalid
     */
    private Optional<UserPrincipal> validateAndExtractPrincipal(String jwt) {
        // Educational implementation: simple lookup
        UserPrincipal principal = tokenCache.get(jwt);

        if (principal != null) {
            return Optional.of(principal);
        }

        // In production, this would parse and validate the actual JWT
        return Optional.empty();
    }

    /**
     * Generates a sample JWT token for a user (educational purposes only).
     *
     * Production implementation would use a proper JWT library:
     * <pre>
     * String token = JWT.create()
     *     .withIssuer("commission-calculator")
     *     .withSubject(userId)
     *     .withClaim("username", username)
     *     .withClaim("roles", roles)
     *     .withExpiresAt(new Date(System.currentTimeMillis() + 3600000))
     *     .sign(Algorithm.HMAC256(secretKey));
     * </pre>
     *
     * @param principal The user principal
     * @return A sample token string
     */
    public String generateSampleToken(UserPrincipal principal) {
        // Generate a simple token identifier
        String token = "token-" + UUID.randomUUID().toString();
        tokenCache.put(token, principal);
        return token;
    }

    /**
     * Gets a sample token for demonstration purposes.
     *
     * @param role The role to get a token for
     * @return A sample token, or null if not found
     */
    public String getSampleToken(UserRole role) {
        if (role == UserRole.SALES_REP) {
            return "sample-token-sales-rep";
        } else if (role == UserRole.SALES_MANAGER) {
            return "sample-token-manager";
        } else if (role == UserRole.SYSTEM_ADMIN) {
            return "sample-token-admin";
        }
        return null;
    }
}